
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'2 7/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'3 3/4 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'2 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'1 7/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'3 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'4 5/6 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'4 5/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'4 9/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'5 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'3 1/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'6 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'3 3/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'4 3/4 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'3 11/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'2 3/4 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'7 9/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'4 7/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'9 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'10 1/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'13/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'7/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'1 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'1 1/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'2 9/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'1 1/2 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'1 3/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'4 3/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'3/4 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'5 1/2 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'6 1/4 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'4 29/32 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'3 1/2 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'3 1/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'2 1/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'1 3/4 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'2 1/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'4 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'1 1/4 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'1 3/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'9 3/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'2 1/4 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'1 5/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'5 3/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'8 1/4 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'5 7/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'4 1/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'6 3/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'10 1/2 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'1 15/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'3 1/4 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'2 1/2 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'12 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'18 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'5 3/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'5 5/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'3 5/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'5 1/4 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'4 1/2 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'7 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'6 3/4 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'4 1/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'6 11/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'1 5/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'4 3/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'4 1/4 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'6 1/2 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'5 9/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'1 7/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'2 5/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'17/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'3.4375 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'3 7/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'3 7/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'4 5/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'5 1/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'6 1/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'9 1/2 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'2 3/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'10 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'14 1/2 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'12 3/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'18 1/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'14 1/4 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'18 1/4 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'9 5/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'9 6/16 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'15 1/8 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'15 W',0,NULL)
insert into [dbo].[SpecificationAttributeOption]([SpecificationAttributeId],[Name],[DisplayOrder],[ColorSquaresRgb]) values(37,'21 W',0,NULL)
